#!/bin/bash
#
# AOI_conv
#
# created: 08.05.2015
# by zinke
#

Usage() {
cat << EOF

    Usage: $0 <srcdir> <odir> [options]

    OPTIONS:
            -fov    field of view of image
            -fr     frame rate (NIY!)
            -dt     data type for output

        ##################################################
        ##            (c) wolf zinke (2015)             ##
        ##        Licensed under the MIT license        ##
        ##################################################


EOF
exit 1

}


if [ $# -lt 1 ]; then
    Usage
else
    srcdir=$1
    odir=$2
    shift 2
fi

#__________________________________________________________________________________________#

dt=""
fov=""
fr=1

while [ $# -gt 0 ] ;
do
    case $1 in
        -fov)   fov=", $2"
                shift 2
                ;;
         -fr)   fr=$2
                shift 2
                ;;
         -dt)   dt=", $2"
                shift 2
                ;;
          -*)   echo "Wrong option: <$1>"
                echo ""
                Usage
                ;;
           *)   break
                ;;
    esac
done

#__________________________________________________________________________________________#

echo "source directory: $srcdir"
echo "output directory: $odir"

mkdir -p $odir  # make sure this directory exists

# convert all *.blk files
for cfl in $(ls $srcdir/*.BLK)
do
    onm=$(basename $cfl | sed -e 's/.BLK//g')

    echo "processing $onm"

    blk2nii $cfl -onm $odir/$onm  # note that FOV and frame rate could be specified
done

# convert all *.bmp files
for cfl in $(ls $srcdir/*.bmp)
do
    onm=$(basename $cfl | sed -e 's/.bmp//g')

    echo "processing $onm"

    bmp2nii $cfl -onm $odir/$onm.nii # note that FOV could be specified
done

# zip the output to save space
for cfl in $(ls $odir/*.nii)
do
    if hash pigz 2>/dev/null # this will help as well to get things done faster
    then
        pigz --best $cfl
    else
#         fslchfiletype NIFTI_GZ $cfl
        gzip --best -q $cfl
    fi
done




