#!/bin/bash
#
# blk2nii
#
# created: 08.04.2015
# by zinke
#

Usage() {
cat << EOF

    Usage: $0 <blkfl> [options]

    OPTIONS:
            -onm    output file name
            -fov    field of view of image
            -dt     data type for output

        ##################################################
        ##            (c) wolf zinke (2015)             ##
        ##        Licensed under the MIT license        ##
        ##################################################


EOF
exit 1

}


if [ $# -lt 1 ]; then
    Usage
else
    blkfl=$1;
    shift
fi

#__________________________________________________________________________________________#


dt=""
fov=""
onm=$(echo "$blkpfl" | cut -d. -f1)

while [ $# -gt 0 ] ;
do
    case $1 in
        -onm)   onm="$2"
                shift 2
                ;;
        -fov)   fov=", $2"
                shift 2
                ;;
         -dt)   dt=", $2"
                shift 2
                ;;
          -*)   echo "Wrong option: <$1>"
                echo ""
                Usage
                ;;
           *)   break
                ;;
    esac
done

#__________________________________________________________________________________________#

toolpath=$(dirname $(which $0))
srcpath=$(dirname $toolpath)
niipath=$(ls -d $srcpath/NIfTI*)


# echo "addpath('$niipath');addpath('$toolpath'); AOI_bmp2nii('$bmpfl' $onm $fov $dt); exit;" | octave --silent --no-window-system -f -H

errmsg=$(echo "addpath('$niipath');addpath('$toolpath'); AOI_blk2nii('$blkfl', '$onm' $fov $dt); exit;" | matlab -nojvm -nodisplay -nosplash -nodesktop)

# fslchfiletype NIFTI_GZ $onm

