#!/bin/bash
#
# blk2nii
#
# created: 08.04.2015
# by zinke
#

Usage() {
cat << EOF

    Usage: $0 <> [options]

    OPTIONS:
            -

        ##################################################
        ##            (c) wolf zinke (2015)             ##
        ##        Licensed under the MIT license        ##
        ##################################################


EOF
exit 1

}


if [ $# -lt 1 ]; then
    Usage
else
    arg1=$1;
    shift
fi

#__________________________________________________________________________________________#

while [ $# -gt 0 ] ;
do
    case $1 in
           -)
                shift
                ;;
          -*)   echo "Wrong option: <$1>"
                echo ""
                Usage
                ;;
           *)   break
                ;;
    esac
done

#__________________________________________________________________________________________#

